#!/bin/sh
#
# Runtime entrypoint hook for the CMTrace.dev container.
#
# Runs from /docker-entrypoint.d/ before the base image execs nginx and
# generates a real_ip / set_real_ip_from snippet from CMTRACE_TRUSTED_PROXIES
# so reverse-proxy X-Forwarded-For headers are honoured for trusted sources
# only.
#
# CMTRACE_TRUSTED_PROXIES accepts whitespace- or comma-separated CIDRs. The
# literal "*" / "all" / "any" expands to 0.0.0.0/0 + ::/0 (trust everything —
# only safe behind a closed network). When unset, defaults to RFC1918 + CGNAT
# + loopback + IPv6 ULA / link-local.
#
# /etc/nginx is backed by a named Docker volume populated from the image on
# first run; its files are world-readable so any PUID:PGID can read them
# without further permission handling.
#
set -eu

RUNTIME_DIR=/tmp/cmtrace-runtime
TRUSTED_PROXIES_FILE="${RUNTIME_DIR}/trusted-proxies.conf"

DEFAULT_CIDRS="10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 ::1/128 fc00::/7 fe80::/10"

RAW="${CMTRACE_TRUSTED_PROXIES:-${DEFAULT_CIDRS}}"

case "${RAW}" in
    "*"|"all"|"any") RAW="0.0.0.0/0 ::/0" ;;
esac

mkdir -p "${RUNTIME_DIR}"

{
    echo "# Generated by /docker-entrypoint.d/$(basename "$0")"
    echo "# Source: CMTRACE_TRUSTED_PROXIES"
    for cidr in $(echo "${RAW}" | tr ',\t\n' '   '); do
        [ -n "${cidr}" ] || continue
        printf 'set_real_ip_from %s;\n' "${cidr}"
    done
    echo "real_ip_header X-Forwarded-For;"
    echo "real_ip_recursive on;"
} > "${TRUSTED_PROXIES_FILE}"

echo "[entrypoint] wrote ${TRUSTED_PROXIES_FILE}"
